export const status = {
  approved: 'Aprovado',
  pending: 'Pendente',
  denied: 'Negado',
  canceled: 'Cancelado',
  completed: 'Concluído',
  inProgress: 'Em andamento',
  waiting: 'Aguardando',
  scheduled: 'Agendado',
  inactive: 'Inativo',
  active: 'Ativo',
  deleted: 'Deletado',
  updated: 'Atualizado',
  created: 'Criado',
  error: 'Erro',
  success: 'Sucesso',
  destructive: 'Destrutivo',
  warning: 'Aviso',
  info: 'Informação',
  default: 'Padrão',
  disapproved: 'Reprovado',
  reproved: 'Reprovado',
  expired: 'Expirado',
} as const
