export const units = {
  kgfPerCm2: 'kgf/cm²',
  celsius: '°C',
  moreLessThreePercents: '± 3%',
  lbfPerIn2: 'lbf/in²',
  m2: 'm²',
  mm: 'mm',
  pol: 'pol',
  un: 'un',
  kgvPerH: 'kgv/h',
  m: 'm',
  mm2: 'mm²',
  mm3: 'mm³',
  m3: 'm³',
  cv: 'CV',
  ph: 'pH',
  min: 'min',
  percentage: '%',
} as const
